### ISSUE TITLE
circular dependency in imports

### ISSUE THREAD

**Issue by apredixfan** [PredixDev/px-defaults-design#2]
Tried to import "px-normalize-design/_generic.normalize.scss", but bumped into an error while building.

Error: An @import loop has been found:
px-normalize-design/_generic.normalize.scss imports px-defaults-design/_settings.defaults.scss
px-defaults-design/_settings.defaults.scss imports px-functions-design/_tools.functions.scss
px-functions-design/_tools.functions.scss imports px-defaults-design/_settings.defaults.scss

_tools.functions.scss and _settings.defaults.scss imports the other.

**Comment by randyaskin** [comment]
Please see https://github.com/PredixDev/px-functions-design/issues/1

**Comment by tallaxes** [comment]
Just run into this. This appears to be introduced by the recent switch to depend on px-functions-design v0.3.3, as px-functions-design now (starting from 0.3.0?) [imports px-defaults-design](https://github.com/PredixDev/px-functions-design/commit/cc6f8656958b9cf4ac372646f99a8b4d2f65ee17) ...
